@extends('layouts.app')

@section('title', 'Privacy and Terms of Use')

@section('content')
<div style="display: flex; flex-direction: column; max-width: 90%; margin-block: 3rem 5rem; line-height: 1.5rem; word-break: break-word;">
    <h2 style="line-height: 3rem;">PRIVACY NOTICE</h2>
    <em>Last updated January 15th, 2023</em>
    <p>This privacy notice for Full-Stack Dan ("Company," "we," "us," or "our"), describes how and why we might collect, store, use, and/or share ("process") your information when you use our services ("Services"), such as when you: Questions or concerns? Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at ddgroleau.developer@gmail.com.</p>
    <h2 style="line-height: 3rem">SUMMARY OF KEY POINTS</h2>
    <p><strong>What personal information do we process?</strong>  When you visit, use, or navigate our Services, we may process personal information depending on how you interact with https://fullstackdan.com and the Services, the choices you make, and the products and features you use.</p>
    <p><strong>Do we process any sensitive personal information?</strong> We do not process sensitive personal information.</p>
    <p><strong>Do we receive any information from third parties? </strong>We may receive information from public databases, marketing partners, social media platforms, and other outside sources.</p>
    <p><strong>How do we process your information? </strong>We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so.</p>
    <p><strong>In what situations and with which parties do we share personal information? </strong>We may share information in specific situations and with specific third parties.</p>
    <p><strong>What are your rights? </strong>Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information.</p>
    <p><strong>How do you exercise your rights? </strong>The easiest way to exercise your rights is by contacting us. We will consider and act upon any request in accordance with applicable data protection laws.</p>
    <h2 style="line-height: 3rem">TABLE OF CONTENTS</h2>
    <ol>
        <li>WHAT INFORMATION DO WE COLLECT?</li>
        <li>HOW DO WE PROCESS YOUR INFORMATION?</li>
        <li>WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</li>
        <li>DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</li>
        <li>HOW DO WE HANDLE YOUR SOCIAL LOGINS?</li>
        <li>IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</li>
        <li>HOW LONG DO WE KEEP YOUR INFORMATION?</li>
        <li>DO WE COLLECT INFORMATION FROM MINORS?</li>
        <li>WHAT ARE YOUR PRIVACY RIGHTS?</li>
        <li>CONTROLS FOR DO-NOT-TRACK FEATURES</li>
        <li>DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</li>
        <li>DO WE MAKE UPDATES TO THIS NOTICE?</li>
        <li>HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</li>
        <li>HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</li>
    </ol>
    <h3>1. WHAT INFORMATION DO WE COLLECT?</h3>
    <h4>Personal information you disclose to us</h4>
    <p><em><strong>In Short:</strong> We collect personal information that you provide to us.</em></p>
    <p>We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.</p>
    <p><em><strong>Sensitive Information.</strong> We do not process sensitive information.</em></p>
    <p>All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.</p>
    <h4>Information automatically collected</h4>
    <p><em><strong>In Short: </strong>Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Services.</em></p>
    <p>We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.</p>
    <p>Like many businesses, we also collect information through cookies and similar technologies.</p>
    <h3>2. HOW DO WE PROCESS YOUR INFORMATION?</h3>
    <p><em><strong>In Short: </strong>We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.</em></p>
    <p>We process your personal information for a variety of reasons, depending on how you interact with our Services, including your email address when you contact us.</p>
    <h3>3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</h3>
    <p><em><strong>In Short: </strong>We may share information in specific situations described in this section and/or with the following third parties.</em></p>
    <p>We may need to share your personal information in the following situations:</p>
    <ul>
        <li>Business Transfers. We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</li>
        <li>Affiliates. We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy notice. Affiliates include our parent company and any subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.</li>
        <li>Business Partners. We may share your information with our business partners to offer you certain products, services, or promotions.</li>
    </ul>
    <h3>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</h3>
    <p><em><strong>In Short: </strong>We may use cookies and other tracking technologies to collect and store your information.</em></p>
    <p>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice.</p>
    <h3>5. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</h3>
    <p><em><strong>In Short: </strong>If you choose to register or log in to our services using a social media account, we may have access to certain information about you.</em></p>
    <p>Our Services offer you the ability to register and log in using your third-party social media account details (like your Facebook or Twitter logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile information we receive may vary depending on the social media provider concerned, but will often include your name, email address, friends list, and profile picture, as well as other information you choose to make public on such a social media platform.</p>
    <p>We will use the information we receive only for the purposes that are described in this privacy notice or that are otherwise made clear to you on the relevant Services. Please note that we do not control, and are not responsible for, other uses of your personal information by your third-party social media provider. We recommend that you review their privacy notice to understand how they collect, use, and share your personal information, and how you can set your privacy preferences on their sites and apps.</p>
    <h3>6. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</h3>
    <p><em><strong>In Short: </strong>We may transfer, store, and process your information in countries other than your own.</em></p>
    <p>Our servers are located in the United States of America. If you are accessing our Services from outside, please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those third parties with whom we may share your personal information (see "WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?" above), in and other countries.</p>
    <p>If you are a resident in the European Economic Area (EEA) or United Kingdom (UK), then these countries may not necessarily have data protection laws or other similar laws as comprehensive as those in your country. However, we will take all necessary measures to protect your personal information in accordance with this privacy notice and applicable law.</p>
    <h3>7. HOW LONG DO WE KEEP YOUR INFORMATION?</h3>
    <p><em><strong>In Short: </strong>We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law.</em></p>
    <p>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than 3 years.</p>
    <p>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</p>
    <h3>8. DO WE COLLECT INFORMATION FROM MINORS?</h3>
    <p><em><strong>In Short: </strong>We do not knowingly collect data from or market to children under 18 years of age.</em></p>
    <p>We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent's use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at ddgroleau.developer@gmail.com.</p>
    <h3>9. WHAT ARE YOUR PRIVACY RIGHTS?</h3>
    <p><em><strong>In Short: </strong>You may review, change, or terminate your account at any time.</em></p>
    <p>If you are located in the EEA or UK and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm.</p>
    <p>If you are located in Switzerland, the contact details for the data protection authorities are available here: https://www.edoeb.admin.ch/edoeb/en/home.html.</p>
    <p><em><strong>Withdrawing your consent:</strong>If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section "HOW CAN YOU CONTACT US ABOUT THIS NOTICE?" below.</em></p>
    <p>However, please note that this will not affect the lawfulness of the processing before its withdrawal nor, when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.</p>
    <h4>Account Information</h4>
    <p>If you would at any time like to review or change the information in your account or terminate your account, you can contact us. Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms and/or comply with applicable legal requirements.</p>
    <h3>10. CONTROLS FOR DO-NOT-TRACK FEATURES</h3>
    <p>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ("DNT") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.</p>
    <h3>11. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</h3>
    <p><em><strong>In Short: </strong>Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.</em></p>
    <p>California Civil Code Section 1798.83, also known as the "Shine The Light" law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</p>
    <p>If you are under 18 years of age, reside in California, and have a registered account with Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g., backups, etc.).</p>
    <h3>12. DO WE MAKE UPDATES TO THIS NOTICE?</h3>
    <p><em><strong>In Short: </strong>Yes, we will update this notice as necessary to stay compliant with relevant laws.</em></p>
    <p>We may update this privacy notice from time to time. The updated version will be indicated by an updated "Revised" date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.</p>
    <h3>13. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</h3>
    <p>If you have questions or comments about this notice, you may email us at ddgroleau.developer@gmail.com.</p>
    <h3>14. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h3>
    <p>Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it. To request to review, update, or delete your personal information, please contact us.</p>
</div>
<div style="display: flex; flex-direction: column; max-width: 90%; padding-block: 0px 5rem; line-height: 1.5rem; word-break: break-word;">
    <h2 style="line-height: 3rem;">TERMS OF SERVICE</h2>
    <p><em>Last updated January 15th, 2023</em></p>
    <h3>TABLE OF CONTENTS</h3>
    <ol>
        <li><span style="font-weight: 400;"> AGREEMENT TO TERMS</span></li>
        <li><span style="font-weight: 400;"> INTELLECTUAL PROPERTY RIGHTS</span></li>
        <li><span style="font-weight: 400;"> USER REPRESENTATIONS</span></li>
        <li><span style="font-weight: 400;"> PROHIBITED ACTIVITIES</span></li>
        <li><span style="font-weight: 400;"> USER GENERATED CONTRIBUTIONS</span></li>
        <li><span style="font-weight: 400;"> CONTRIBUTION LICENSE</span></li>
        <li><span style="font-weight: 400;"> SUBMISSIONS</span></li>
        <li><span style="font-weight: 400;"> THIRD-PARTY WEBSITE AND CONTENT</span></li>
        <li><span style="font-weight: 400;"> SITE MANAGEMENT</span></li>
        <li><span style="font-weight: 400;"> PRIVACY POLICY</span></li>
        <li><span style="font-weight: 400;"> TERM AND TERMINATION</span></li>
        <li><span style="font-weight: 400;"> MODIFICATIONS AND INTERRUPTIONS</span></li>
        <li><span style="font-weight: 400;"> GOVERNING LAW</span></li>
        <li><span style="font-weight: 400;"> DISPUTE RESOLUTION</span></li>
        <li><span style="font-weight: 400;"> CORRECTIONS</span></li>
        <li><span style="font-weight: 400;"> DISCLAIMER</span></li>
        <li><span style="font-weight: 400;"> LIMITATIONS OF LIABILITY</span></li>
        <li><span style="font-weight: 400;"> INDEMNIFICATION</span></li>
        <li><span style="font-weight: 400;"> USER DATA</span></li>
        <li><span style="font-weight: 400;"> ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</span></li>
        <li><span style="font-weight: 400;"> CALIFORNIA USERS AND RESIDENTS</span></li>
        <li><span style="font-weight: 400;"> MISCELLANEOUS</span></li>
        <li><span style="font-weight: 400;"> CONTACT US</span></li>
    </ol>
    <h2 style="line-height: 3rem">1. AGREEMENT TO TERMS</h2>
    <p><span style="font-weight: 400;">These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and Full-Stack Dan ("</span><strong>Company</strong><span style="font-weight: 400;">," “</span><strong>we</strong><span style="font-weight: 400;">," “</span><strong>us</strong><span style="font-weight: 400;">," or “</span><strong>our</strong><span style="font-weight: 400;">”), concerning your access to and use of the</span><a href="https://fullstackdan.com/">https://fullstackdan.com</a><span style="font-weight: 400;"> website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”).</span><span style="font-weight: 400;"> You agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.</span></p>
    <p><span style="font-weight: 400;">Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Use at any time and for any reason. We will alert you about any changes by updating the “Last updated” date of these Terms of Use, and you waive any right to receive specific notice of each such change. Please ensure that you check the applicable Terms every time you use our Site so that you understand which Terms apply. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms of Use by your continued use of the Site after the date such revised Terms of Use are posted.</span></p>
    <p><span style="font-weight: 400;">The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</span></p>
    <p><span style="font-weight: 400;">The Site is not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use this Site. You may not use the Site in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</span></p>
    <p><span style="font-weight: 400;">The Site is intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Site.</span></p>
    <h2 style="line-height: 3rem">2. INTELLECTUAL PROPERTY RIGHTS</h2>
    <p><span style="font-weight: 400;">Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, international copyright laws, and international conventions. The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. Except as expressly provided in these Terms of Use, no part of the Site and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</span></p>
    <p><span style="font-weight: 400;">Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.</span></p>
    <h2 style="line-height: 3rem">3. USER REPRESENTATIONS</h2>
    <p><span style="font-weight: 400;">By using the Site, you represent and warrant that:</span> <span style="font-weight: 400;">(1) you have the legal capacity and you agree to comply with these Terms of Use; (2) you are not a minor in the jurisdiction in which you reside; (3) you will not access the Site through automated or non-human means, whether through a bot, script, or otherwise; (4) you will not use the Site for any illegal or unauthorized purpose; and (5) your use of the Site will not violate any applicable law or regulation.</span></p>
    <p><span style="font-weight: 400;">If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof).</span></p>
    <h2 style="line-height: 3rem">4. PROHIBITED ACTIVITIES</h2>
    <p><span style="font-weight: 400;">You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</span></p>
    <p><span style="font-weight: 400;">As a user of the Site, you agree not to:</span></p>
    <ul>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Use any information obtained from the Site in order to harass, abuse, or harm another person.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Make improper use of our support services or submit false reports of abuse or misconduct.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Use the Site in a manner inconsistent with any applicable laws or regulations.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Engage in unauthorized framing of or linking to the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Delete the copyright or other proprietary rights notice from any Content.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Attempt to impersonate another user or person or use the username of another user.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site to you.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or launching any unauthorized script or other software.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Use a buying agent or purchasing agent to make purchases on the Site.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Use the Site as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or commercial enterprise.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Use the Site to advertise or offer to sell goods and services.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Sell or otherwise transfer your profile.</span></li>
    </ul>
    <h2 style="line-height: 3rem">5. USER GENERATED CONTRIBUTIONS</h2>
    <p><span style="font-weight: 400;">The Site does not offer users to submit or post content. We may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions"). Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated in accordance with the Site Privacy Policy. When you create or make available any Contributions, you thereby represent and warrant that:</span></p>
    <ul>
        <li style="font-weight: 400;"><span style="font-weight: 400;">The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">You are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms of Use.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Site and these Terms of Use.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions are not false, inaccurate, or misleading.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not violate any applicable law, regulation, or rule.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not violate the privacy or publicity rights of any third party.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.</span></li>
        <li style="font-weight: 400;"><span style="font-weight: 400;">Your Contributions do not otherwise violate, or link to material that violates, any provision of these Terms of Use, or any applicable law or regulation.</span></li>
    </ul>
    <p><span style="font-weight: 400;">Any use of the Site in violation of the foregoing violates these Terms of Use and may result in, among other things, termination or suspension of your rights to use the Site.</span></p>
    <h2 style="line-height: 3rem">6. CONTRIBUTION LICENSE</h2>
    <p><span style="font-weight: 400;">You agree that we may access, store, process, and use any information and personal data that you provide following the terms of the Privacy Policy and your choices (including settings).</span></p>
    <p><span style="font-weight: 400;">By submitting suggestions or other feedback regarding the Site, you agree that we can use and share such feedback for any purpose without compensation to you.</span></p>
    <p><span style="font-weight: 400;">We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Site. You are solely responsible for your Contributions to the Site and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</span></p>
    <h2 style="line-height: 3rem">7. SUBMISSIONS</h2>
    <p><span style="font-weight: 400;">You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Site ("Submissions") provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you. You hereby waive all moral rights to any such Submissions, and you hereby warrant that any such Submissions are original with you or that you have the right to submit such Submissions. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions.</span></p>
    <h2 style="line-height: 3rem">8. THIRD-PARTY WEBSITE AND CONTENT</h2>
    <p><span style="font-weight: 400;">The Site may contain (or you may be sent via the Site) links to other websites ("Third-Party Websites") as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or originating from third parties ("Third-Party Content"). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Site or any Third-Party Content posted on, available through, or installed from the Site, including the content, accuracy, offensiveness, opinions, reliability, privacy practices, or other policies of or contained in the Third-Party Websites or the Third-Party Content. Inclusion of, linking to, or permitting the use or installation of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us. If you decide to leave the Site and access the Third-Party Websites or to use or install any Third-Party Content, you do so at your own risk, and you should be aware these Terms of Use no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any website to which you navigate from the Site or relating to any applications you use or install from the Site. Any purchases you make through Third-Party Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third party. You agree and acknowledge that we do not endorse the products or services offered on Third-Party Websites and you shall hold us harmless from any harm caused by your purchase of such products or services. Additionally, you shall hold us harmless from any losses sustained by you or harm caused to you relating to or resulting in any way from any Third-Party Content or any contact with Third-Party Websites.</span></p>
    <h2 style="line-height: 3rem">9. SITE MANAGEMENT</h2>
    <p><span style="font-weight: 400;">We reserve the right, but not the obligation, to: (1) monitor the Site for violations of these Terms of Use; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms of Use, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Site or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Site in a manner designed to protect our rights and property and to facilitate the proper functioning of the Site.</span></p>
    <h2 style="line-height: 3rem">10. PRIVACY POLICY</h2>
    <p><span style="font-weight: 400;">We care about data privacy and security. By using the Site, you agree to be bound by our Privacy Policy posted on the Site, which is incorporated into these Terms of Use. Please be advised the Site is hosted in </span><span style="font-weight: 400;">the United States</span><span style="font-weight: 400;">. If you access the Site from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in </span><span style="font-weight: 400;">the United States</span><span style="font-weight: 400;">, then through your continued use of the Site, you are transferring your data to </span><span style="font-weight: 400;">the United States</span><span style="font-weight: 400;">, and you agree to have your data transferred to and processed in </span><span style="font-weight: 400;">the United States</span><span style="font-weight: 400;">.</span></p>
    <h2 style="line-height: 3rem">11. TERM AND TERMINATION</h2>
    <p><span style="font-weight: 400;">These Terms of Use shall remain in full force and effect while you use the Site. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS OF USE, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SITE (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OF USE OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SITE OR DELETE ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</span></p>
    <p><span style="font-weight: 400;">If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</span></p>
    <h2 style="line-height: 3rem">12. MODIFICATIONS AND INTERRUPTIONS</h2>
    <p><span style="font-weight: 400;">We reserve the right to change, modify, or remove the contents of the Site at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Site. We also reserve the right to modify or discontinue all or part of the Site without notice at any time. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Site.</span></p>
    <p><span style="font-weight: 400;">We cannot guarantee the Site will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Site, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Site at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Site during any downtime or discontinuance of the Site. Nothing in these Terms of Use will be construed to obligate us to maintain and support the Site or to supply any corrections, updates, or releases in connection therewith.</span></p>
    <h2 style="line-height: 3rem">13. GOVERNING LAW</h2>
    <p><span style="font-weight: 400;">These Terms of Use and your use of the Site are governed by and construed in accordance with the laws of the State of Maine applicable to agreements made and to be entirely performed within the State of Maine, without regard to its conflict of law principles.</span></p>
    <h2 style="line-height: 3rem">14. DISPUTE RESOLUTION</h2>
    <p><strong>Informal Negotiations</strong></p>
    <p><span style="font-weight: 400;">To expedite resolution and control the cost of any dispute, controversy, or claim related to these Terms of Use (each "Dispute" and collectively, the “Disputes”) brought by either you or us (individually, a “Party” and collectively, the “Parties”), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.</span></p>
    <p><strong>Binding Arbitration</strong></p>
    <p><span style="font-weight: 400;">If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved through binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the AAA website:</span> <a href="http://www.adr.org/">www.adr.org</a><span style="font-weight: 400;">. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in Cumberland, Maine. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</span></p>
    <p><span style="font-weight: 400;">If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in Cumberland, Maine, and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts. Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) is excluded from these Terms of Use.</span></p>
    <p><span style="font-weight: 400;">In no event shall any Dispute brought by either Party related in any way to the Site be commenced more than one (1) years after the cause of action arose. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable, and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</span></p>
    <p><strong>Restrictions</strong></p>
    <p><span style="font-weight: 400;">The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.</span></p>
    <p><strong>Exceptions to Informal Negotiations and Arbitration</strong></p>
    <p><span style="font-weight: 400;">The Parties agree that the following Disputes are not subject to the above provisions concerning informal negotiations and binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</span></p>
    <h2 style="line-height: 3rem">15. CORRECTIONS</h2>
    <p><span style="font-weight: 400;">There may be information on the Site that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Site at any time, without prior notice.</span></p>
    <h2 style="line-height: 3rem">16. DISCLAIMER</h2>
    <p><span style="font-weight: 400;">THE SITE IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SITE AND OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SITE AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SITE AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SITE, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</span></p>
    <h2 style="line-height: 3rem">17. LIMITATIONS OF LIABILITY</h2>
    <p><span style="font-weight: 400;">IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</span></p>
    <h2 style="line-height: 3rem">18. INDEMNIFICATION</h2>
    <p><span style="font-weight: 400;">You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) use of the Site; (2) breach of these Terms of Use; (3) any breach of your representations and warranties set forth in these Terms of Use; (4) your violation of the rights of a third party, including but not limited to intellectual property rights; or (5) any overt harmful act toward any other user of the Site with whom you connected via the Site. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</span></p>
    <h2 style="line-height: 3rem">19. USER DATA</h2>
    <p><span style="font-weight: 400;">We will maintain certain data that you transmit to the Site for the purpose of managing the performance of the Site, as well as data relating to your use of the Site. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Site. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</span></p>
    <h2 style="line-height: 3rem">20. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</h2>
    <p><span style="font-weight: 400;">Visiting the Site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SITE. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</span></p>
    <h2 style="line-height: 3rem">21. CALIFORNIA USERS AND RESIDENTS</h2>
    <p><span style="font-weight: 400;">If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.</span></p>
    <h2 style="line-height: 3rem">22. MISCELLANEOUS</h2>
    <p><span style="font-weight: 400;">These Terms of Use and any policies or operating rules posted by us on the Site or in respect to the Site constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. These Terms of Use operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Terms of Use is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Use and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms of Use or use of the Site. You agree that these Terms of Use will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Terms of Use and the lack of signing by the parties hereto to execute these Terms of Use.</span></p>
    <p><span style="font-weight: 400;">It is our policy to not offer our services to any individual or entity whose business activities may include activities of a political, religious, or violent nature, or could be construed as political, religious, or violent. We reserve the right to deny any individual or entity access to our services if we believe they may now or in the future violate this policy.</span></p>
    <h2 style="line-height: 3rem">23. CONTACT US</h2>
    <p><span style="font-weight: 400;">In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:</span></p>
    <p><strong>Full-Stack Dan</strong></p>
    <p><strong>Portland, ME 04102</strong></p>
    <p><strong>United States</strong></p>
    <p><strong>ddgroleau.developer@gmail.com</strong></p>
</div>
<div style="display: flex; flex-direction: column; max-width: 90%; padding-block: 0px 5rem; line-height: 1.5rem; word-break: break-word;">
    <h2 style="line-height: 3rem;">DISCLAIMER AND COOKIE POLICY</h2>
    <p><em>Last updated January 15th, 2023</em></p>
    <h2 style="line-height: 3rem">DISCLAIMER</h2>
    <h3>WEBSITE DISCLAIMER</h3>
    <p>The information provided by Full-Stack Dan ("we," "us," or "our") on https://fullstackdan.com (the "Site") and our mobile application is for general informational purposes only. All information on the Site and our mobile application is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or our mobile application. UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR OUR MOBILE APPLICATION OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE AND OUR MOBILE APPLICATION. YOUR USE OF THE SITE AND OUR MOBILE APPLICATION AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE AND OUR MOBILE APPLICATION IS SOLELY AT YOUR OWN RISK.</p>
    <br>
    <h2 style="line-height: 3rem">COOKIE POLICY</h2>
    <p>This Cookie Policy explains how Full-Stack Dan ("Company", "we", "us", and "our") uses cookies and similar technologies to recognize you when you visit our websites at<a href="https://fullstackdan.com/">&nbsp;https://fullstackdan.com</a>, ("Websites"). It explains what these technologies are and why we use them, as well as your rights to control our use of them.</p>
    <p>In some cases we may use cookies to collect personal information, or that becomes personal information if we combine it with other information.</p>
    <h3>What are cookies?</h3>
    <p>Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.</p>
    <p>Cookies set by the website owner (in this case, Full-Stack Dan) are called "first party cookies". Cookies set by parties other than the website owner are called "third party cookies". Third party cookies enable third party features or functionality to be provided on or through the website (e.g. like advertising, interactive content and analytics). The parties that set these third party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.</p>
    <h3>Why do we use cookies?</h3>
    <p>We use first and third party cookies for several reasons. Some cookies are required for technical reasons in order for our Websites to operate, and we refer to these as "essential" or "strictly necessary" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Online Properties. Third parties serve cookies through our Websites for advertising, analytics and other purposes. This is described in more detail below.</p>
    <p>The specific types of first and third party cookies served through our Websites and the purposes they perform are described below (please note that the specific cookies served may vary depending on the specific Online Properties you visit):
    <ul>
        <li>Google Analytics</li>
    </ul>
    </p>
    <h3>How can I control cookies?</h3>
    <p>You may set or amend your web browser controls to accept or refuse cookies. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information.</p>
    <p>In addition, most advertising networks offer you a way to opt out of targeted advertising. If you would like to find out more information, please visit&nbsp;<a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>or&nbsp;<a href="http://www.youronlinechoices.com/">http://www.youronlinechoices.com</a>.</p>
    <h3>What about other tracking technologies, like web beacons?</h3>
    <p>Cookies are not the only way to recognize or track visitors to a website. We may use other, similar technologies from time to time, like web beacons (sometimes called "tracking pixels" or "clear gifs"). These are tiny graphics files that contain a unique identifier that enable us to recognize when someone has visited our Websites or opened an e-mail including them. This allows us, for example, to monitor the traffic patterns of users from one page within a website to another, to deliver or communicate with cookies, to understand whether you have come to the website from an online advertisement displayed on a third-party website, to improve site performance, and to measure the success of e-mail marketing campaigns. In many instances, these technologies are reliant on cookies to function properly, and so declining cookies will impair their functioning.</p>
    <h3>Do you use Flash cookies or Local Shared Objects?</h3>
    <p>Websites may also use so-called "Flash Cookies" (also known as Local Shared Objects or "LSOs") to, among other things, collect and store information about your use of our services, fraud prevention and for other site operations.</p>
    <p>If you do not want Flash Cookies stored on your computer, you can adjust the settings of your Flash player to block Flash Cookies storage using the tools contained in the&nbsp;<a href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html">Website Storage Settings Panel</a>. You can also control Flash Cookies by going to the&nbsp;<a href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager03.html">Global Storage Settings Panel</a>and following the instructions (which may include instructions that explain, for example, how to delete existing Flash Cookies (referred to "information" on the Macromedia site), how to prevent Flash LSOs from being placed on your computer without your being asked, and (for Flash Player 8 and later) how to block Flash Cookies that are not being delivered by the operator of the page you are on at the time).</p>
    <p>Please note that setting the Flash Player to restrict or limit acceptance of Flash Cookies may reduce or impede the functionality of some Flash applications, including, potentially, Flash applications used in connection with our services or online content.</p>
    <h3>Do you serve targeted advertising?</h3>
    <p>Third parties may serve cookies on your computer or mobile device to serve advertising through our Websites. These companies may use information about your visits to this and other websites in order to provide relevant advertisements about goods and services that you may be interested in. They may also employ technology that is used to measure the effectiveness of advertisements. This can be accomplished by them using cookies or web beacons to collect information about your visits to this and other sites in order to provide relevant advertisements about goods and services of potential interest to you. The information collected through this process does not enable us or them to identify your name, contact details or other details that directly identify you unless you choose to provide these.</p>
    <h3>How often will you update this Cookie Policy?</h3>
    <p>We may update this Cookie Policy from time to time in order to reflect, for example, changes to the cookies we use or for other operational, legal or regulatory reasons. Please therefore re-visit this Cookie Policy regularly to stay informed about our use of cookies and related technologies.</p>
    <p>The date at the top of this Cookie Policy indicates when it was last updated.</p>
    <h3>Where can I get further information?</h3>
    <p>If you have any questions about our use of cookies or other technologies, please email us at ddgroleau.developer@gmail.com.</p>
</div>
<div style="display: flex; flex-direction: column; max-width: 90%; padding-block: 0px 5rem; line-height: 1.5rem; word-break: break-word;">
    <h2 style="line-height: 3rem;">Full-Stack Dan Accessibility Statement</h2>
    <p><em>Last Updated: January 15th, 2023.</em></p>
    <h2 style="line-height: 3rem">General</h2>
    <p>At Full-Stack Dan, we strive to ensure our services are accessible to all people. In order to achieve this, we have invested important resources into our site so that it is available to people with disabilities. We truly believe that website accessibility efforts are vital in ensuring that all users deserve the right to independence, equality, and ease of use.</p>
    <h2 style="line-height: 3rem">Accessibility on https://fullstackdan.com/</h2>
    <p>Using <a href="https://checker.org">accessibility checker.org's</a> audit tool, https://fullstackdan.com has been scanned for compliance according to the Web Content Accessibility Guidelines (WCAG 2.1). Since performing the audit, Full-Stack Dan continues to raise its accessibility standards, with a goal of exceeding those required by the <a href="https://www.ada.gov/">ADA</a>.</p>
    <h2 style="line-height: 3rem">Disclaimer</h2>
    <p>At Full-Stack Dan, we are dedicated to continually updating and improving the accessibility of the site and services. We believe it is our responsibility and mutual moral obligation to provide access to all users.</p>
    <p>As we seek to continually adjust and improve accessibility issues on this site, we also commit to regularly scanning https://fullstackdan.com with <a href="https://checker.org">accessibility checker's</a> scanner.</p>
    <p>Our goal is to identify and rectify every accessibility barrier on our site. Although we strive to ensure all pages and content on https://fullstackdan.com are fully accessible, it is possible some website content has not yet been fully adjusted to adhere to the most strict accessibility standards. For this reason, we are here for you.</p>
    <p>If you have any issues with accessing content or using https://fullstackdan.com, or should you need assistance with any part of the website, please don't hesitate to let us know. You are welcome to contact us during normal business hours, and we will be more than happy to help. Please see contact details below.</p>
    <h2 style="line-height: 3rem">Contact Us</h2>
    <p>Have questions, need assistance, or want to report an accessibility issue? Please contact Full-Stack Dan Customer Support:</p>
    <p>Email: <a href="mailto:ddgroleau.developer@gmail.com">ddgroleau.developer@gmail.com</a></p>
</div>
@endsection