version: '3.8'
services:
    laravel:
        container_name: portfolio_v3
        restart: always
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            APP_NAME: portfolio_v3
            APP_ENV: production
            APP_DEBUG: true
            APP_URL: https://fullstackdan.com
            LOG_CHANNEL: stack
            LOG_DEPRECATIONS_CHANNEL: null
            LOG_LEVEL: debug
        volumes:
            - '.:/var/www/html'
        networks:
            - webnet

networks:
    webnet:
        name: ${APP_NETWORK}

